// <auto-generated />
using System;
using CodeArena.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeArena.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404210306_SeedExtraChallenges")]
    partial class SeedExtraChallenges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeArena.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CodeArena.Data.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8754),
                            Description = "Write a function that takes two numbers and returns their sum.\n Example: Input: 3, 5 → Output: 8.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "sum-two-numbers",
                            Tags = "math",
                            Title = "Sum Two Numbers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8760),
                            Description = "Write a program that prints numbers from 1 to 100.\n For multiples of 3, print 'Fizz' instead of the number, for multiples of 5 print 'Buzz', and for multiples of both 3 and 5 print 'FizzBuzz'.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "fizzbuzz",
                            Tags = "loops",
                            Title = "FizzBuzz"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8761),
                            Description = "Write a function that reverses a given string.\n Example: Input: 'hello' → Output: 'olleh'.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "reverse-a-string",
                            Tags = "strings, algorithms",
                            Title = "Reverse a String"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8763),
                            Description = "Write a function that returns the factorial of a given non-negative integer n.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "factorial",
                            Tags = "recursion, math",
                            Title = "Factorial"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8764),
                            Description = "Determine if a given string is a palindrome.\n Example: 'racecar' → true, 'hello' → false.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "palindrome-check",
                            Tags = "strings, algorithms",
                            Title = "Palindrome Check"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8765),
                            Description = "Return the first n numbers of the Fibonacci sequence.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "fibonacci-sequence",
                            Tags = "recursion, math, algorithms",
                            Title = "Fibonacci Sequence"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8766),
                            Description = "Write a function that finds the maximum number in a given array.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "find-maximum-in-array",
                            Tags = "array, algorithms",
                            Title = "Find Maximum in Array"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8767),
                            Description = "Given two sorted arrays, merge them into one sorted array.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "merge-two-sorted-arrays",
                            Tags = "array, sorting, algorithms",
                            Title = "Merge Two Sorted Arrays"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8768),
                            Description = "Count the number of vowels in a given string.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "count-vowels",
                            Tags = "strings",
                            Title = "Count Vowels"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8769),
                            Description = "Reverse the order of words in a sentence. Example: 'Hello World' → 'World Hello'.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "reverse-words-in-sentence",
                            Tags = "strings, algorithms",
                            Title = "Reverse Words in Sentence"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8770),
                            Description = "Return the sum of all elements in a given integer array.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "sum-of-array-elements",
                            Tags = "array, math",
                            Title = "Sum of Array Elements"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8771),
                            Description = "Return a new array with all duplicates removed from the original array.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "remove-duplicates-from-array",
                            Tags = "array, algorithms",
                            Title = "Remove Duplicates from Array"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8773),
                            Description = "Check if a given number is a prime number.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "prime-number-check",
                            Tags = "math, algorithms",
                            Title = "Prime Number Check"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8774),
                            Description = "Return the intersection elements of two arrays.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "intersection-of-two-arrays",
                            Tags = "array, algorithms",
                            Title = "Intersection of Two Arrays"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8775),
                            Description = "Encrypt a string using a Caesar cipher with a given shift value.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "caesar-cipher",
                            Tags = "strings, algorithms, encryption",
                            Title = "Caesar Cipher"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8776),
                            Description = "Return the second largest number from an array of integers.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "find-second-largest",
                            Tags = "array, algorithms",
                            Title = "Find Second Largest"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8777),
                            Description = "Calculate the sum of digits of a given integer.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "sum-of-digits",
                            Tags = "math, recursion",
                            Title = "Sum of Digits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8778),
                            Description = "Rotate an array to the right by k steps.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "rotate-array",
                            Tags = "array, algorithms",
                            Title = "Rotate Array"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8779),
                            Description = "Check if a string of brackets is balanced.\n Example: '{[()]}'' → true, '{[(])}' → false.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "balanced-brackets",
                            Tags = "stack, algorithms, strings",
                            Title = "Balanced Brackets"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8780),
                            Description = "Count the number of words in a given sentence.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "count-words-in-string",
                            Tags = "strings",
                            Title = "Count Words in String"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8781),
                            Description = "Given a collection of intervals, merge all overlapping intervals.",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Slug = "merge-intervals",
                            Tags = "array, algorithms, sorting",
                            Title = "Merge Intervals"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8782),
                            Description = "Find the length of the longest substring without repeating characters.",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Slug = "longest-substring-without-repeating-characters",
                            Tags = "strings, algorithms, sliding-window",
                            Title = "Longest Substring Without Repeating Characters"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8783),
                            Description = "Find the missing number in an array containing n distinct numbers taken from 0 to n.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "find-missing-number",
                            Tags = "array, math",
                            Title = "Find Missing Number"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8785),
                            Description = "Find the longest common prefix string amongst an array of strings.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "longest-common-prefix",
                            Tags = "strings, algorithms",
                            Title = "Longest Common Prefix"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8786),
                            Description = "Check if two strings are anagrams of each other.",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Slug = "valid-anagram",
                            Tags = "strings, algorithms",
                            Title = "Valid Anagram"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 4, 4, 21, 3, 6, 185, DateTimeKind.Utc).AddTicks(8815),
                            Description = "Check if a number is a power of two.",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Slug = "power-of-two",
                            Tags = "math, bit-manipulation",
                            Title = "Power of Two"
                        });
                });

            modelBuilder.Entity("CodeArena.Data.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionCode")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CodeArena.Data.Models.XpTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("XpAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId", "ChallengeId", "Reason")
                        .IsUnique()
                        .HasFilter("[ChallengeId] IS NOT NULL");

                    b.ToTable("XpTransactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CodeArena.Data.Models.Submission", b =>
                {
                    b.HasOne("CodeArena.Data.Models.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArena.Data.Models.ApplicationUser", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeArena.Data.Models.XpTransaction", b =>
                {
                    b.HasOne("CodeArena.Data.Models.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId");

                    b.HasOne("CodeArena.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CodeArena.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CodeArena.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArena.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CodeArena.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeArena.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CodeArena.Data.Models.Challenge", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
